---
- name: Download script
  ansible.builtin.get_url:
    dest: /tmp
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh
    mode: 700
    owner: root
    group: root

- name: Execute script
  ansible.builtin.shell:
    cmd: /tmp/script.rpm.sh

- name: Export var name
  ansible.builtin.shell:
    cmd: export EXTERNAL_URL="https://gitlab.example.com"

- name: Install Gitlab
  ansible.builtin.yum:
    name: gitlab-ee
    update_cache: yes
    state: present
