---
- name: Set hostname to gitlab.example.com
  ansible.builtin.hostname:
   name: gitlab.example.com

- name: Install packages
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present

  notify:
   - Start and enable postfix
   - Add firewall rules
   - Reload firewall
