---
# tasks file for gitlab
#
- name: Install required packages
  ansible.builtin.include_tasks:
    file: install_packages.yml

- name: Add Gitlab repo task
  ansible.builtin.include_tasks:
    file: add_gitlab_repo.yml

- name: Basic configuration
  ansible.builtin.include_tasks:
    file: post_install_config.yml
