---
# handlers file for gitlab
- name: Start and enable postfix
  ansible.builtin.systemd:
    name: postfix
    state: started
    enabled: yes


- name: Add firewall rules
  ansible.posix.firewalld:
    immediate: yes
    permanent: yes
    service: "{{ fw_rule }}"
    state: enabled
  loop: "{{ firewall_rules }}"
  loop_control:
   loop_var: fw_rule

- name: Reload firewall
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded 
